[versions]
# libraries
junit = "5.12.1"
junitPlatformLauncher = "1.12.1"
junit4 = "4.13.2"
kodeinDi = "7.25.0"
coroutines = "1.10.1"

# plugins
intelliJPlatform = "2.1.0"
kotlin = "2.1.20"

[libraries]
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatformLauncher" }
kodeinDiJvm = { group = "org.kodein.di", name = "kodein-di-jvm", version.ref = "kodeinDi" }
coroutinesCoreJvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
